---
# Source: kubeit-app-of-apps/templates/applications.yaml
# Reference ArgoCD application definition - https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yamlmap[applications:[map[chart:map[path:deploy] containerOS:linux environments:[map[clusterColour:[blue dev017] name:dev namespaces:[standard standard-test] region:[eastus2]]] name:standard-workload namespace:management-test]] chart:map[ignoreMissingValueFiles:false path:kubeit-charts/charts/kubeit-deployment-chart skipCrds:true] clusterColour:blue clusterSubdomain:dev017 dnsDomain:kubeit.dnv.com env:dev global:map[chart:map[ignoreMissingValueFiles:false path:kubeit-charts/charts/kubeit-deployment-chart skipCrds:true]] ingressType:internal region:eastus2 shortRegion:eus2 targetRevision:main tenantMultiRegion:false tenantName:tenant2 tenantPodIdentityName:admin-pod-identity]

# https://docs.microsoft.com/en-us/azure/devops/organizations/settings/naming-restrictions?view=azure-devops


# ArgoCD Image Updater Variables
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: standard-workload-standard
  namespace:
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: "standard"
    server: 'https://kubernetes.default.svc'
  project: "tenant2"
  source:
    repoURL: ""
    targetRevision: "main"
    path: "deploy"
    helm:
      ignoreMissingValueFiles: false
      skipCrds: true
      valueFiles:
        - appValues/global.yaml
        - appValues/standard-workload/appGlobal.yaml
        - appValues/standard-workload/environment/dev/dev.yaml
        - appValues/standard-workload/environment/dev/region/eastus2/eastus2.yaml
        - appValues/standard-workload/environment/dev/region/eastus2/cluster/blue.yaml
        - appValues/standard-workload/environment/dev/region/eastus2/cluster/namespaces/standard.yaml
      values: |
        global:
          app: standard-workload
          namespace: standard
          gateway:
            name: istio-system/global-https-internal-default-gateway
          defaultRouting:
            kubeitDefaultHosts:
              dnsDomain: "kubeit.dnv.com"
              tenantMultiRegion: "false"
          kubeit:
            region: "eastus2"
            namespace: "standard"
            clusterSubdomain: "dev017"
            clusterColour: "blue"
            ingressType: "internal"
            shortRegion: "eus2"
            tenantName: "tenant2"
            environmentName: "dev"
            tenantPodIdentityName: "admin-pod-identity"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=false

    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
---
# Source: kubeit-app-of-apps/templates/applications.yaml
# https://docs.microsoft.com/en-us/azure/devops/organizations/settings/naming-restrictions?view=azure-devops


# ArgoCD Image Updater Variables
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: standard-workload-standard-test
  namespace:
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: "standard-test"
    server: 'https://kubernetes.default.svc'
  project: "tenant2"
  source:
    repoURL: ""
    targetRevision: "main"
    path: "deploy"
    helm:
      ignoreMissingValueFiles: false
      skipCrds: true
      valueFiles:
        - appValues/global.yaml
        - appValues/standard-workload/appGlobal.yaml
        - appValues/standard-workload/environment/dev/dev.yaml
        - appValues/standard-workload/environment/dev/region/eastus2/eastus2.yaml
        - appValues/standard-workload/environment/dev/region/eastus2/cluster/blue.yaml
        - appValues/standard-workload/environment/dev/region/eastus2/cluster/namespaces/standard-test.yaml
      values: |
        global:
          app: standard-workload
          namespace: standard-test
          gateway:
            name: istio-system/global-https-internal-default-gateway
          defaultRouting:
            kubeitDefaultHosts:
              dnsDomain: "kubeit.dnv.com"
              tenantMultiRegion: "false"
          kubeit:
            region: "eastus2"
            namespace: "standard-test"
            clusterSubdomain: "dev017"
            clusterColour: "blue"
            ingressType: "internal"
            shortRegion: "eus2"
            tenantName: "tenant2"
            environmentName: "dev"
            tenantPodIdentityName: "admin-pod-identity"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=false

    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
