---
defaultRouting:
  kubeitDefaultHosts:
    hostsPrefix: "www-test"      # Application will be available under: https://${hostsPrefix}-${tenantName}.${env}.kubeit.dnv.com/, instead of https://${app}-${tenantName}.${env}.kubeit.dnv.com/

env:
  KUBERNETES_NAMESPACE: standard-test
  MESSAGE: "Hello on standard-test namespace!"

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi
