---
defaultRouting:
  kubeitDefaultHosts:
    hostsPrefix: "www"      # Application will be available under: https://${hostsPrefix}-${tenantName}.${env}.kubeit.dnv.com/, instead of https://${app}-${tenantName}.${env}.kubeit.dnv.com/

env:
  KUBERNETES_NAMESPACE: standard
  MESSAGE: "Hello on standard namespace!"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 700m
    memory: 128Mi
