---
applications: &apps
  - name: standard-workload
    containerOS: linux
    chart:
      path: deploy
    environments:
      - name: dev
        namespaces:
          - standard
          - standard-test
        region:
          - westeurope
        clusterColour:
          - blue
          - dev001

global:
  chart:
    ignoreMissingValueFiles: true
    skipCrds: true
  applications: *apps
