---
applications: &apps
  - name: standard-workload
    containerOS: linux
    chart:
      repoURL: https://dnv-gssit.github.io/kubeit-example-complex
      name: kubeit-deployment-chart
      targetRevision: "1.0.8"
    environments:
      - name: dev
        namespaces:
          - standard
          - standard-test
        region:
          - westeurope
        clusterColour:
          - blue
          - dev001

global:
  chart:
    ignoreMissingValueFiles: true
    skipCrds: true
  applications: *apps
