---
applications: &apps
  - name: standard-workload
    containerOS: linux
    environments:
      - name: dev
        namespaces:
          - standard
          - standard-test
        region:
          - westeurope
        clusterColour:
          - blue
          - dev001

global:
  chart:
    path: kubeit-charts/charts/kubeit-deployment-chart
    ignoreMissingValueFiles: true
    skipCrds: true
  applications: *apps
