---
applications: &apps
  - name: standard-workload
    containerOS: linux
    environments:
      - name: dev
        namespaces:
          - standard
          - standard-test
        region:
          - westeurope
        clusterColour:
          - blue
          - dev001

global:
  chart:
    repoURL: https://dnv-gssit.github.io/kubeit-example-complex
    chart: kubeit-deployment-chart
    targetRevison: "1.0.8"
    ignoreMissingValueFiles: true
    skipCrds: true
  applications: *apps
