# Merge global to Values
{{- mergeOverwrite .Values (deepCopy (default (dict) .Values.global)) -}}
{{- if .Values.alertmanagerconfig.enabled }}
{{- range $config:= .Values.alertmanagerconfig.alerts }}
{{- range $secret:= $config.receivers }}
---
apiVersion: v1
kind: Secret
metadata:
  name: teams-notification-webhook
type: Opaque
data:
  webhook: {{ .secret }} # base64 encorded secret
{{- end }}
{{- end }}
{{- end }}
