{
 "title": "Prometheus Alerts",
 "description": "Dashboard showing Prometheus Alerts (both pending and firing) for alerts adjustment and debugging",
 "tags": [
  "prometheus",
  "alerts"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Alerts History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ALERTS", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Firing alerts",
   "type": "table",
   "description": "Shows how many times was particular alert started in a defined time range. Alert can be started either directly as `firing` or as a `pending`. Pending alerts wait for a defined time before it flips to a `firing` alert. This is specified with the `FOR` clause in a Prometheus `rules` file.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ALERTS{alertstate=~\"firing\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending alerts",
   "type": "table",
   "description": "Shows how many times was particular alert started in a defined time range. Alert can be started either directly as `firing` or as a `pending`. Pending alerts wait for a defined time before it flips to a `firing` alert. This is specified with the `FOR` clause in a Prometheus `rules` file.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ALERTS{alertstate=~\"pending\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}