---
global:
  defaultRouting:
    kubeitDefaultHosts:
      hostsPrefix: "www"      # Application will be available under: https://${hostsPrefix}-${tenantName}.${env}.kubeit.dnv.com/, instead of https://${app}-${tenantName}.${env}.kubeit.dnv.com/

  env:
    KUBERNETES_NAMESPACE: standard
    MESSAGE: "Hello on standard namespace!"

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 700m
      memory: 128Mi
  service:
    kubeitTcpServiceEnabled: true
    exposeInternalLoadBalancer: true
    port: 10008
    type: LoadBalancer

  authorizationPolicy:
    enabled: false
  requestAuthentication:
    enabled: false
  vpa:
    enabled: true
    minCPU: 300m
    maxCPU: 1
    minMem: 300Mi
    maxMem: 800Mi
    minReplicas: 1
    containerName: "*"
