---
global:
  # Workload info
  workload:
    type: standard      # Required - standard or onegateway
    state: stateful     # Required - stateful or stateless, for stateless mounting extra volumes is blocked (besides keyvault)

  image:
    repository: "kubeitglobalsvcauxacrwe.azurecr.io/test/hello-kubernetes"
    tag: "1.5"
    containerPort: 8080

  # service:
  #   port: 8080

  defaultRouting:
    enabled: true
    kubeitDefaultHosts:
      hostsPrefix: "www"      # Application will be available under: https://${hostsPrefix}-${tenantName}.${env}.kubeit.dnv.com/, instead of https://${app}-${tenantName}.${env}.kubeit.dnv.com/
    rewriteUrlPrefix:
      enabled: false
    allHosts: false
    redirectOnNoTrailingSlash: false
    catchAll: true

  authorizationPolicy:
    enabled: false
  requestAuthentication:
    enabled: false

  # TODO: add volumes
  # volumes:

  # Be Aware! Security contexts configuration is specific to Docker Image, if your workload is not spinning up try disabling settings below and after check what needs to be changed.
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsNonRoot: true

  containerSecurityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true

  # https://github.com/paulbouwer/hello-kubernetes/tree/main/src/app
  env:
    MESSAGE: "Hello on standard workload!"

  alertmanagerconfig:
    enabled: true
    alerts:
      - name: example
        groupBy: ["alertname", "job"]
        groupWait: 30s
        groupInterval: 5m
        repeatInterval: 12h
        continue: true
        routes:
          matcher:
            - name: tenant
              matchType: =
              value: "tenantName"
            - name: namespace
              matchType: =~
              value: "tenant2"
        receiver: gssit-alert-manager
        receivers:
          - name: gssit-alert-manager
            secret: dGVzdA==
            webhookConfigs:
              - urlSecret:
                  key: webhook
                  name: teams-notifications-webhook
