---
# Global values for all environments
global:
  keyVaultSecrets:
    enabled: true
  vpa:
    enabled: false
    minCPU: 300m
    maxCPU: 1
    minMem: 300Mi
    maxMem: 500Mi
    minReplicas: 1
    containerName: "*"
  azureKeyVaultSecrets:
    # type: csi-keyvault                                   # Type of the secret controller used to deploy the secrets inside the KubeIT cluster
    # tenantId: "adf10e2b-b6e9-41d6-be2f-c12bb566019c"     # Azure Active Directory Tenant ID
    # clientId: ""                                         # Managed Identity Application ID - use Active Directory to pull this value or ask the Cluster Admin team to provide it
    # azureKeyVaults:
    #   - azureKeyVaultName: KubeIT-DEV-KV-SH-WE                  # Name of the Azure KeyVault
    #     secrets:
    #       - k8sSecretName: testSecret                    # Name of the Kubernetes secret resource that is going to be created inside the cluster
    #         data:
    #           - k8sSecretKey: k8sSecretKey               # Name of the key in Kubernetes secret resource
    #             azureKeyVaultSecretName: certificate-key-le-dev      # Name of the secret in Azure KeyVault to pull the secret value from
    #           - k8sSecretKey: k8sSecretKey2              # It is possible to define multiple secret keys and values in one secretproviderclass - lines below show example how to do that
    #             azureKeyVaultSecretName: SecretName2
    #       - k8sSecretName: testSecret2
    #         data:
    #           - k8sSecretKey: k8sSecretKey3
    #             azureKeyVaultSecretName: SecretName3
    #           - k8sSecretKey: k8sSecretKey3
    #             azureKeyVaultSecretName: SecretName3
    #   - azureKeyVaultName: testkeyvault2                       # Name of the Azure KeyVault
    #     secrets:
    #       - k8sSecretName: testkeyvault2                    # Name of the Kubernetes secret resource that is going to be created inside the cluster
    #         data:
    #           - k8sSecretKey: k8sSecretKey               # Name of the key in Kubernetes secret resource
    #             azureKeyVaultSecretName: SecretName4      # Name of the secret in Azure KeyVault to pull the secret value from
    #           - k8sSecretKey: k8sSecretKey4              # It is possible to define multiple secret keys and values in one secretproviderclass - lines below show example how to do that
    #             azureKeyVaultSecretName: SecretName4
    #       - k8sSecretName: testSecret5
    #         data:
    #           - k8sSecretKey: k8sSecretKey5
    #             azureKeyVaultSecretName: SecretName5
    #           - k8sSecretKey: k8sSecretKey5
    #             azureKeyVaultSecretName: SecretName5
