# Merge global to Values
{{- mergeOverwrite .Values (deepCopy (default (dict) .Values.global)) -}}
{{- if not .Values.deploymentOnly -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-service.serviceName" . }}
  labels:
    app.kubernetes.io/name: {{ include "platform-service.name" . }}
    helm.sh/chart: {{ include "platform-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.service.kubeitTcpServiceEnabled }}
    kubeitTcpServiceEnabled: "true"
    kubeitTcpServicePort: "{{ .Values.service.port }}"
{{- end }}

{{- if .Values.service.exposeInternalLoadBalancer }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "30"
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ required "service.port must be specified" .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- if .Values.service.additionalPortConfig }}
{{ .Values.service.additionalPortConfig | toYaml | trim | indent 4 }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "platform-service.name" . }}
    app: {{ .Values.app }}
{{- end}}
