
# Merge global to Values
{{- mergeOverwrite .Values (deepCopy (default (dict) .Values.global)) -}}
{{- if .Values.vpa.enabled }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "platform-service.serviceName" . }}-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "platform-service.serviceName" . }}-vpa
  resourcePolicy:
    containerPolicies:
      - containerName: "{{ .Values.vpa.containerName }}"
        minAllowed:
          cpu: {{ .Values.vpa.minCPU }}
          memory: {{ .Values.vpa.minMem }}
        maxAllowed:
          cpu: {{ .Values.vpa.maxCPU }}
          memory: {{ .Values.vpa.maxMem }}
        controlledResources: ["cpu", "memory"]
{{- end }}
