---
name: ci

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ["main", "update-apps-of-apps"]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - uses: pre-commit/action@v3.0.0
